import type {
  Ciclo,
  EsforcoRelativo,
  FaseLog,
  Metrica,
  Perfil,
  Portfolio,
  Projeto,
  ProjetoStatus,
  Sessao,
  Tarefa,
  Veredito,
} from '../lib/tipos'

/** Stable demo IDs used in routes (`/projeto/demo-p01`). */
export const DEMO_P01 = 'demo-p01'
export const DEMO_P00 = 'demo-p00'
export const DEMO_CICLO = 'demo-ciclo-3'
export const DEMO_GABRIEL = 'demo-perfil-gabriel'
export const DEMO_GUSTAVO = 'demo-perfil-gustavo'

const HOJE = new Date()
function isoDiasAtras(n: number) {
  const d = new Date(HOJE)
  d.setDate(d.getDate() - n)
  return d.toISOString().slice(0, 10)
}

export const DEMO_PERFIS: Perfil[] = [
  {
    id: DEMO_GABRIEL,
    user_id: null,
    nome: 'Gabriel',
    papel: 'produto_tech',
    titulo: 'Produto & Tecnologia',
    dominios: ['Arquitetura Luau', 'IA e pipeline', 'Segurança', 'Dashboard', 'Publicação'],
    metricas_chave: ['sistema funcionando', 'zero exploit', 'build no teto'],
    cota_ciclo: [
      '1 marco funcional entregue',
      'Checklist §7.3 aplicada',
      'Métricas atualizadas no dashboard',
    ],
    ritmo: 'contínuo, blocos longos',
    ativo: true,
  },
  {
    id: DEMO_GUSTAVO,
    user_id: null,
    nome: 'Gustavo',
    papel: 'growth',
    titulo: 'Growth & Mercado',
    dominios: ['Ícone / thumbnail / título', 'Vídeo TikTok/Shorts', 'Pesquisa Fase 0', 'Playtest', 'Ads $50'],
    metricas_chave: ['CTR', 'visitantes únicos', 'alcance dos vídeos'],
    cota_ciclo: ['3 vídeos postados', '1 lote de arte', '1 pesquisa ou playtest'],
    ritmo: 'assíncrono, noites, lotes',
    ativo: true,
  },
]

export const DEMO_CICLO_ATIVO: Ciclo = {
  id: DEMO_CICLO,
  numero: 3,
  inicio: isoDiasAtras(4),
  fim: isoDiasAtras(-2),
  objetivo: 'Manter #01 na janela de observação sem feature creep; Gustavo ataca thumbnail e vídeo.',
  status: 'ativo',
  analise_fechamento: null,
  contestacoes: null,
}

export const DEMO_ESFORCO: EsforcoRelativo[] = [
  {
    ciclo: 3,
    inicio: DEMO_CICLO_ATIVO.inicio,
    fim: DEMO_CICLO_ATIVO.fim,
    ciclo_status: 'ativo',
    nome: 'Gabriel',
    titulo: 'Produto & Tecnologia',
    horas_declaradas: 30,
    horas_realizadas: 24,
    pct_realizado: 80,
    sessoes: 5,
    tarefas_concluidas: 2,
    tarefas_atribuidas: 3,
  },
  {
    ciclo: 3,
    inicio: DEMO_CICLO_ATIVO.inicio,
    fim: DEMO_CICLO_ATIVO.fim,
    ciclo_status: 'ativo',
    nome: 'Gustavo',
    titulo: 'Growth & Mercado',
    horas_declaradas: 10,
    horas_realizadas: 9,
    pct_realizado: 90,
    sessoes: 3,
    tarefas_concluidas: 2,
    tarefas_atribuidas: 2,
  },
]

export const DEMO_PROJETOS: Projeto[] = [
  {
    id: DEMO_P01,
    codigo: '#01',
    nome: 'Street Tycoon',
    genero_base: 'Tycoon (clone com tração recente)',
    uma_frase: 'Construa um negócio de rua e desbloqueie upgrades com Robux.',
    core_loop: ['Coletar', 'Melhorar o stand', 'Desbloquear a próxima rua'],
    alteracao_unica: 'Eventos de rua a cada 10 minutos com recompensa limitada',
    modelo_monetizacao: 'Game Pass de 2x cash + passes cosméticos de stand',
    fase_atual: 'f4_observacao',
    data_inicio: isoDiasAtras(38),
    data_lancamento: isoDiasAtras(10),
    data_fim_observacao: isoDiasAtras(-4),
    data_arquivamento: null,
    roblox_universe_id: null,
    roblox_url: 'https://www.roblox.com/games/example/Street-Tycoon',
    gasto_ads_total: 28,
    ativo: true,
  },
  {
    id: DEMO_P00,
    codigo: '#00',
    nome: 'Hello Purchase',
    genero_base: 'Obby trivial (prova de cano)',
    uma_frase: 'Jogo-teste para validar publicação e compra real.',
    core_loop: ['Correr', 'Pular', 'Chegar ao fim'],
    alteracao_unica: 'Nenhuma — só provar o cano',
    modelo_monetizacao: '1 Game Pass de skip',
    fase_atual: 'f5_veredito',
    data_inicio: isoDiasAtras(60),
    data_lancamento: isoDiasAtras(45),
    data_fim_observacao: isoDiasAtras(31),
    data_arquivamento: isoDiasAtras(30),
    roblox_universe_id: null,
    roblox_url: null,
    gasto_ads_total: 0,
    ativo: false,
  },
]

export const DEMO_STATUS: ProjetoStatus[] = [
  {
    id: DEMO_P01,
    codigo: '#01',
    nome: 'Street Tycoon',
    fase_atual: 'f4_observacao',
    data_inicio: DEMO_PROJETOS[0].data_inicio,
    data_lancamento: DEMO_PROJETOS[0].data_lancamento,
    data_fim_observacao: DEMO_PROJETOS[0].data_fim_observacao,
    fase_desde: isoDiasAtras(10),
    dias_na_fase: 10,
    ultima_atividade: isoDiasAtras(1),
    dias_parado: 1,
    visitantes_unicos: 320,
    d1_retention: 8.2,
    sessao_media_min: 4.1,
    ccu_pico: 12,
    robux_dia: 40,
    estourou_build: false,
    parado_demais: false,
    observacao_encerrada: false,
    status: 'em_observacao',
    semaforo: '🟡',
  },
  {
    id: DEMO_P00,
    codigo: '#00',
    nome: 'Hello Purchase',
    fase_atual: 'f5_veredito',
    data_inicio: DEMO_PROJETOS[1].data_inicio,
    data_lancamento: DEMO_PROJETOS[1].data_lancamento,
    data_fim_observacao: DEMO_PROJETOS[1].data_fim_observacao,
    fase_desde: isoDiasAtras(30),
    dias_na_fase: 30,
    ultima_atividade: isoDiasAtras(30),
    dias_parado: 30,
    visitantes_unicos: 620,
    d1_retention: 4.0,
    sessao_media_min: 2.5,
    ccu_pico: 8,
    robux_dia: 0,
    estourou_build: false,
    parado_demais: false,
    observacao_encerrada: true,
    status: 'flopando',
    semaforo: '🔴',
  },
]

export const DEMO_PORTFOLIO: Portfolio = {
  em_projeto: 0,
  em_build: 0,
  em_observacao: 1,
  lucrando: 0,
  flopando: 1,
  problema_descoberta: 0,
  arquivados: 1,
  alertas: 1,
  total: 2,
  robux_acumulado: 8400,
  usd_estimado: 31.92,
  robux_faltando_m0: 21600,
}

export const DEMO_FASES_LOG: Record<string, FaseLog[]> = {
  [DEMO_P01]: [
    {
      id: 'demo-fl-01-f4',
      projeto_id: DEMO_P01,
      fase: 'f4_observacao',
      entrou_em: isoDiasAtras(10),
      saiu_em: null,
      justificativa: null,
      movido_por: DEMO_GABRIEL,
    },
    {
      id: 'demo-fl-01-f3',
      projeto_id: DEMO_P01,
      fase: 'f3_polimento',
      entrou_em: isoDiasAtras(15),
      saiu_em: isoDiasAtras(10),
      justificativa: null,
      movido_por: DEMO_GUSTAVO,
    },
    {
      id: 'demo-fl-01-f2',
      projeto_id: DEMO_P01,
      fase: 'f2_build',
      entrou_em: isoDiasAtras(36),
      saiu_em: isoDiasAtras(15),
      justificativa: null,
      movido_por: DEMO_GABRIEL,
    },
    {
      id: 'demo-fl-01-f1',
      projeto_id: DEMO_P01,
      fase: 'f1_definicao',
      entrou_em: isoDiasAtras(37),
      saiu_em: isoDiasAtras(36),
      justificativa: null,
      movido_por: DEMO_GABRIEL,
    },
    {
      id: 'demo-fl-01-f0',
      projeto_id: DEMO_P01,
      fase: 'f0_research',
      entrou_em: isoDiasAtras(38),
      saiu_em: isoDiasAtras(37),
      justificativa: null,
      movido_por: DEMO_GUSTAVO,
    },
  ],
  [DEMO_P00]: [
    {
      id: 'demo-fl-00-f5',
      projeto_id: DEMO_P00,
      fase: 'f5_veredito',
      entrou_em: isoDiasAtras(30),
      saiu_em: null,
      justificativa: 'Janela encerrada — registrar aprendizado.',
      movido_por: DEMO_GABRIEL,
    },
  ],
}

export const DEMO_METRICAS: Record<string, Metrica[]> = {
  [DEMO_P01]: [
    {
      id: 'demo-m-01-a',
      projeto_id: DEMO_P01,
      data: isoDiasAtras(1),
      visitantes_unicos: 320,
      visitas: 410,
      d1_retention: 8.2,
      sessao_media_min: 4.1,
      ccu_pico: 12,
      robux_dia: 40,
      gasto_ads_dia: 5,
      ctr: 2.1,
      registrado_por: DEMO_GABRIEL,
    },
    {
      id: 'demo-m-01-b',
      projeto_id: DEMO_P01,
      data: isoDiasAtras(3),
      visitantes_unicos: 210,
      visitas: 280,
      d1_retention: 7.5,
      sessao_media_min: 3.8,
      ccu_pico: 9,
      robux_dia: 25,
      gasto_ads_dia: 5,
      ctr: 1.8,
      registrado_por: DEMO_GABRIEL,
    },
    {
      id: 'demo-m-01-c',
      projeto_id: DEMO_P01,
      data: isoDiasAtras(5),
      visitantes_unicos: 95,
      visitas: 120,
      d1_retention: 6.0,
      sessao_media_min: 3.2,
      ccu_pico: 5,
      robux_dia: 10,
      gasto_ads_dia: 8,
      ctr: 1.4,
      registrado_por: DEMO_GUSTAVO,
    },
  ],
  [DEMO_P00]: [
    {
      id: 'demo-m-00-a',
      projeto_id: DEMO_P00,
      data: isoDiasAtras(32),
      visitantes_unicos: 620,
      visitas: 800,
      d1_retention: 4.0,
      sessao_media_min: 2.5,
      ccu_pico: 8,
      robux_dia: 0,
      gasto_ads_dia: 0,
      ctr: 3.0,
      registrado_por: DEMO_GABRIEL,
    },
  ],
}

export const DEMO_VEREDICTOS: Record<string, Veredito | null> = {
  [DEMO_P01]: null,
  [DEMO_P00]: {
    id: 'demo-v-00',
    projeto_id: DEMO_P00,
    data: isoDiasAtras(30),
    visitantes_unicos_janela: 620,
    gate_amostra: true,
    d1_observado: 4.0,
    sessao_observada: 2.5,
    ccu_observado: 8,
    gate_d1: false,
    gate_sessao: false,
    gate_ccu: false,
    resultado: 'falhou',
    post_mortem:
      'Amostra passou (620 ≥ 500), então o problema foi de produto, não de descoberta. Loop trivial demais: ninguém voltou. Aprendizado: #00 cumpriu o papel de provar o cano de publicação/compra; não era um jogo. Próximo: clonar um gênero com retenção real.',
  },
}

export const DEMO_SESSOES: Sessao[] = [
  {
    id: 'demo-s-1',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    perfil_id: DEMO_GABRIEL,
    data: isoDiasAtras(1),
    duracao_min: 90,
    entrega: 'Corrigido bug de DataStore no save do cash; tested retry path.',
    bloqueios: null,
    proxima_acao: 'Registrar snapshot de métricas amanhã',
    notas: null,
    criado_em: isoDiasAtras(1) + 'T22:00:00Z',
  },
  {
    id: 'demo-s-2',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    perfil_id: DEMO_GUSTAVO,
    data: isoDiasAtras(2),
    duracao_min: 75,
    entrega: '3 thumbnails A/B + 1 Short postado (hook de 3s no stand upgrade).',
    bloqueios: 'CTR ainda baixo no ícone B',
    proxima_acao: 'Trocar ícone amanhã e medir 48h',
    notas: null,
    criado_em: isoDiasAtras(2) + 'T02:00:00Z',
  },
]

export const DEMO_TAREFAS: Tarefa[] = [
  {
    id: 'demo-t-1',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    responsavel_id: DEMO_GUSTAVO,
    titulo: 'Trocar ícone B e medir CTR 48h',
    descricao: 'Ícone atual perde no Creator Dashboard. Substituir e anotar CTR.',
    fase_relacionada: 'f4_observacao',
    prioridade: 'alta',
    status: 'em_andamento',
    prazo: isoDiasAtras(-1),
    resultado: null,
    notas: null,
    contestada: false,
    resposta_claude: null,
    respondida_em: null,
    horas_gastas: null,
    criada_por: 'claude',
    criado_em: isoDiasAtras(3) + 'T12:00:00Z',
    concluida_em: null,
  },
  {
    id: 'demo-t-2',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    responsavel_id: DEMO_GABRIEL,
    titulo: 'Snapshot de métricas (dia 10)',
    descricao: 'Copiar visitantes, D1, sessão, CCU e Robux do Creator Dashboard.',
    fase_relacionada: 'f4_observacao',
    prioridade: 'alta',
    status: 'pendente',
    prazo: isoDiasAtras(0),
    resultado: null,
    notas: null,
    contestada: false,
    resposta_claude: null,
    respondida_em: null,
    horas_gastas: null,
    criada_por: 'claude',
    criado_em: isoDiasAtras(2) + 'T12:00:00Z',
    concluida_em: null,
  },
  {
    id: 'demo-t-3',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    responsavel_id: DEMO_GUSTAVO,
    titulo: 'Postar 2 Shorts esta semana',
    descricao: 'Foco nos primeiros 60s do jogo — onde o churn acontece.',
    fase_relacionada: 'f4_observacao',
    prioridade: 'media',
    status: 'pendente',
    prazo: isoDiasAtras(-3),
    resultado: null,
    notas: 'Um Short já saiu; falta o segundo.',
    contestada: false,
    resposta_claude: null,
    respondida_em: null,
    horas_gastas: 1.5,
    criada_por: 'gustavo',
    criado_em: isoDiasAtras(4) + 'T12:00:00Z',
    concluida_em: null,
  },
  {
    id: 'demo-t-4',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    responsavel_id: DEMO_GABRIEL,
    titulo: 'Hotfix: duplo cash em edge case de leave',
    descricao: null,
    fase_relacionada: 'f4_observacao',
    prioridade: 'alta',
    status: 'concluida',
    prazo: isoDiasAtras(2),
    resultado: 'Fix no servidor: cash só credita após validação de distância + cooldown.',
    notas: null,
    contestada: false,
    resposta_claude: null,
    respondida_em: null,
    horas_gastas: 2,
    criada_por: 'gabriel',
    criado_em: isoDiasAtras(5) + 'T12:00:00Z',
    concluida_em: isoDiasAtras(2) + 'T18:00:00Z',
  },
  {
    id: 'demo-t-5',
    ciclo_id: DEMO_CICLO,
    projeto_id: DEMO_P01,
    responsavel_id: DEMO_GUSTAVO,
    titulo: 'Lote de 3 thumbnails A/B',
    descricao: null,
    fase_relacionada: 'f4_observacao',
    prioridade: 'media',
    status: 'concluida',
    prazo: isoDiasAtras(3),
    resultado: '3 variações no drive + thumbnail A publicada.',
    notas: null,
    contestada: false,
    resposta_claude: null,
    respondida_em: null,
    horas_gastas: 2,
    criada_por: 'claude',
    criado_em: isoDiasAtras(6) + 'T12:00:00Z',
    concluida_em: isoDiasAtras(3) + 'T03:00:00Z',
  },
]

export function demoProjeto(id: string) {
  return DEMO_PROJETOS.find((p) => p.id === id) ?? null
}

export function demoStatus(id: string) {
  return DEMO_STATUS.find((p) => p.id === id) ?? null
}

/** Map logged-in socio name to demo perfil id (real UUIDs differ from fixtures). */
export function demoPerfilIdPorNome(nome: string | undefined | null) {
  if (!nome) return DEMO_GABRIEL
  const p = DEMO_PERFIS.find((x) => x.nome.toLowerCase() === nome.toLowerCase())
  return p?.id ?? DEMO_GABRIEL
}
